name: Deploy Pages

# è§¦å‘æ¡ä»¶ï¼šåœ¨ push åˆ° gh-pages-source åˆ†æ”¯åŽ
on:
  push:
    branches:
      - gh-pages-source

# ä»»åŠ¡
jobs:
  # https://github.com/JamesIves/github-pages-deploy-action
  build-and-deploy:
    name: Deploy GitHub Pages
    # æœåŠ¡å™¨çŽ¯å¢ƒï¼š Ubuntuï¼ˆæœ€æ–°ç‰ˆï¼‰
    runs-on: ubuntu-latest
    steps:
      # æ‹‰å–ä»£ç 
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # ç”Ÿæˆé™æ€æ–‡ä»¶
      - name: Install and Build Static Files ðŸ”§
        # èŽ·å–åœ¨Repoè®¾ç½®çš„Secretï¼ˆClient IDã€Client Secretï¼‰
        env:
          # Vssue Config
          Platform: github
          Owner: yokefellow
          Repo: yokefellow.github.io
          ClientID: ${{ secrets.VSSUE_CLIENT_ID }}
          ClientSecret: ${{ secrets.VSSUE_CLIENT_SECRET }}
          #Google Analytics Config
          GoogleAnalyticsID: G-H4CPPTTMRB
        run: |
          yarn install
          yarn run build
          echo 'yokefellow.cn' > CNAME
      # éƒ¨ç½²åˆ° GitHub Pages
      - name: Deploy GitHub Pages ðŸš€
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_branch: main
          publish_dir: ./dist
          commit_message: ðŸš€ ${{ github.event.head_commit.message }} to main branch from @
          enable_jekyll: true
